import Layout from "../components/Layout";
import {
  FaUserGraduate,
  FaChalkboardTeacher,
  FaClipboardList,
  FaCertificate,
  FaFileDownload,
  FaChartBar,
} from "react-icons/fa";

export default function Reports() {
  const reports = [
    {
      title: "Student Report",
      description: "Export student demographic and academic records",
      icon: <FaUserGraduate />,
    },
    {
      title: "Staff Report",
      description: "Export staff and department records",
      icon: <FaChalkboardTeacher />,
    },
    {
      title: "Enrolment Report",
      description: "Export student enrolment records",
      icon: <FaClipboardList />,
    },
    {
      title: "Certificate Report",
      description: "Export certificate collection records",
      icon: <FaCertificate />,
    },
  ];

  const exportReport = (title) => {
    alert(`${title} export functionality is awaiting backend integration.`);
  };

  return (
    <Layout>
      <div style={styles.container}>
        <div style={styles.header}>
          <div>
            <h1>Reports</h1>
            <p>Generate and export institutional reports</p>
          </div>

          <FaChartBar style={styles.headerIcon} />
        </div>

        <div style={styles.cards}>
          {reports.map((report) => (
            <div key={report.title} style={styles.card}>
              <div style={styles.icon}>{report.icon}</div>

              <h3>{report.title}</h3>

              <p>{report.description}</p>

              <button
                style={styles.btn}
                onClick={() => exportReport(report.title)}
              >
                <FaFileDownload />
                Export Report
              </button>
            </div>
          ))}
        </div>

        <div style={styles.tableCard}>
          <h2>Report History</h2>

          <table style={styles.table}>
            <thead>
              <tr>
                <th>Report Name</th>
                <th>Generated By</th>
                <th>Date Generated</th>
                <th>Status</th>
              </tr>
            </thead>

            <tbody>
              <tr>
                <td colSpan="4" style={styles.empty}>
                  Report history will appear here once connected to the backend.
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </Layout>
  );
}

const styles = {
  container: {
    background: "#f5f6fa",
    minHeight: "100vh",
  },

  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "25px",
  },

  headerIcon: {
    fontSize: "50px",
    color: "#1e3a8a",
  },

  cards: {
    display: "grid",
    gridTemplateColumns: "repeat(4,1fr)",
    gap: "20px",
    marginBottom: "30px",
  },

  card: {
    background: "#fff",
    padding: "25px",
    borderRadius: "12px",
    boxShadow: "0 2px 8px rgba(0,0,0,0.08)",
    textAlign: "center",
  },

  icon: {
    fontSize: "35px",
    color: "#1e3a8a",
    marginBottom: "15px",
  },

  btn: {
    marginTop: "15px",
    background: "#1e3a8a",
    color: "#fff",
    border: "none",
    padding: "12px 16px",
    borderRadius: "8px",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "8px",
    width: "100%",
  },

  tableCard: {
    background: "#fff",
    padding: "20px",
    borderRadius: "12px",
    boxShadow: "0 2px 8px rgba(0,0,0,0.08)",
    overflowX: "auto",
  },

  table: {
    width: "100%",
    borderCollapse: "collapse",
    marginTop: "20px",
  },

  empty: {
    textAlign: "center",
    padding: "25px",
    color: "#6b7280",
  },
};